# Generated by Django 5.1.4 on 2025-01-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Rings', 'Rings'), ('Chains', 'Chains'), ('Pendants', 'Pendants'), ('Bangles', 'Bangles'), ('Anklets', 'Anklets'), ('Necklaces', 'Necklaces'), ('Bracelets', 'Bracelets'), ('Earrings', 'Earrings')], max_length=50, null=True),
        ),
    ]
