# Generated by Django 5.1.5 on 2025-03-04 12:16

import BusinessPartner.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('freezed', 'Freezed')], default='approved', max_length=10)),
                ('bp_code', models.CharField(max_length=50, unique=True)),
                ('term', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True, validators=[BusinessPartner.models.validate_mobile_no])),
                ('landline', models.CharField(blank=True, max_length=15, null=True)),
                ('alternate_landline', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True, validators=[BusinessPartner.models.validate_mobile_no], verbose_name='Mobile No')),
                ('more', models.TextField(blank=True, null=True)),
                ('door_no', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_no', models.CharField(blank=True, max_length=50, null=True)),
                ('complex_name', models.CharField(blank=True, max_length=255, null=True)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('map_location', models.CharField(blank=True, max_length=500, null=True)),
                ('location_guide', models.TextField(blank=True, null=True)),
                ('refered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BusinessPartner.businesspartner')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BusinessPartner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPartnerKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('freezed', 'Freezed')], default='approved', max_length=10)),
                ('bis_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True, validators=[BusinessPartner.models.validate_gst_number])),
                ('msme_no', models.CharField(blank=True, max_length=50, null=True, validators=[BusinessPartner.models.validate_msme_no])),
                ('pan_card_image', models.ImageField(blank=True, null=True, upload_to='pan_card')),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True, validators=[BusinessPartner.models.validate_pan_number])),
                ('tan_no', models.CharField(blank=True, max_length=10, null=True, validators=[BusinessPartner.models.validate_pan_number])),
                ('image', models.ImageField(blank=True, null=True, upload_to='kyc/business_partner/')),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True, validators=[BusinessPartner.models.validate_aadhar_no])),
                ('aadhar_front_image', models.ImageField(blank=True, null=True, upload_to='kyc/aadhar/')),
                ('aadhar_back_image', models.ImageField(blank=True, null=True, upload_to='kyc/aadhar/')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True, validators=[BusinessPartner.models.validate_ifsc_code])),
                ('bank_city', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_state', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('bp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_details', to='BusinessPartner.businesspartner')),
            ],
        ),
        migrations.AddConstraint(
            model_name='businesspartner',
            constraint=models.UniqueConstraint(fields=('business_email',), name='unique_email_ci'),
        ),
    ]
