# Generated by Django 5.1.5 on 2025-03-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='business_email',
            field=models.EmailField(blank=True, default='DEFAULT VALUE', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
