# Generated by Django 5.1.5 on 2025-03-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0003_alter_businesspartner_business_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='business_email',
            field=models.EmailField(default='DEFAULT VALUE', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
