# Generated by Django 5.1.5 on 2025-03-04 17:54

import BusinessPartner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0004_alter_businesspartner_business_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspartnerkyc',
            name='aadhar_back_image',
        ),
        migrations.RemoveField(
            model_name='businesspartnerkyc',
            name='aadhar_front_image',
        ),
        migrations.RemoveField(
            model_name='businesspartnerkyc',
            name='pan_card_image',
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='aadhar_attach',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='kyc/aadhar/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='bis_attachment',
            field=models.FileField(default='DEFAULT VALUE', upload_to='kyc/bis/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='gst_attachment',
            field=models.FileField(default='DEFAULT VALUE', upload_to='kyc/gst/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='msme_attachment',
            field=models.FileField(default='DEFAULT VALUE', upload_to='kyc/msme/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='pan_attachment',
            field=models.FileField(default='DEFAULT VALUE', upload_to='kyc/tan/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='tan_attachment',
            field=models.FileField(default='DEFAULT VALUE', upload_to='kyc/tan/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='aadhar_no',
            field=models.CharField(default='DEFAULT VALUE', max_length=12, validators=[BusinessPartner.models.validate_aadhar_no]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='account_no',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='bank_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='bis_no',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='branch',
            field=models.CharField(default='DEFAULT VALUE', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='gst_no',
            field=models.CharField(default='DEFAULT VALUE', max_length=50, validators=[BusinessPartner.models.validate_gst_number]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='ifsc_code',
            field=models.CharField(default='DEFAULT VALUE', max_length=20, validators=[BusinessPartner.models.validate_ifsc_code]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='kyc/business_partner/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='msme_no',
            field=models.CharField(default='DEFAULT VALUE', max_length=50, validators=[BusinessPartner.models.validate_msme_no]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='pan_no',
            field=models.CharField(default='DEFAULT VALUE', max_length=10, validators=[BusinessPartner.models.validate_pan_number]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='tan_no',
            field=models.CharField(default='DEFAULT VALUE', max_length=10, validators=[BusinessPartner.models.validate_pan_number]),
            preserve_default=False,
        ),
    ]
