# Generated by Django 5.1.5 on 2025-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0005_remove_businesspartnerkyc_aadhar_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='bis_attachment',
            field=models.FileField(upload_to=''),
        ),
    ]
