# Generated by Django 5.1.5 on 2025-03-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0006_alter_businesspartnerkyc_bis_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='aadhar_attach',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='bis_attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='gst_attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='msme_attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='pan_attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='tan_attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
