# Generated by Django 5.1.5 on 2025-03-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0007_alter_businesspartnerkyc_aadhar_attach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='freezed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='freezed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('freezed', 'Freezed'), ('revoked', 'Revoked')], default='approved', max_length=10),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('freezed', 'Freezed'), ('revoked', 'Revoked')], default='approved', max_length=10),
        ),
    ]
