# Generated by Django 5.1.5 on 2025-03-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0008_businesspartner_freezed_businesspartner_revoked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='bis_attachment',
            field=models.ImageField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='gst_attachment',
            field=models.ImageField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='msme_attachment',
            field=models.ImageField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='pan_attachment',
            field=models.ImageField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='tan_attachment',
            field=models.ImageField(upload_to='attachments/'),
        ),
    ]
