# Generated by Django 5.1.5 on 2025-03-05 06:42

import BusinessPartner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0012_remove_businesspartnerkyc_aadhar_attach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='aadhar_attach',
            field=models.FileField(default='DEFAULT VALUE', upload_to='attachments/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='aadhar_no',
            field=models.CharField(default='DEFAULT VALUE', max_length=12, validators=[BusinessPartner.models.validate_aadhar_no]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesspartnerkyc',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BusinessPartnerKYCName',
        ),
    ]
