# Generated by Django 5.1.5 on 2025-03-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0016_alter_businesspartnerkyc_aadhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartnerkyc',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('freezed', 'Freezed'), ('revoked', 'Revoked')], max_length=10),
        ),
    ]
