# Generated by Django 5.1.5 on 2025-03-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0017_alter_businesspartnerkyc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='refered_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
