# Generated by Django 5.1.5 on 2025-03-11 08:35

import BusinessPartner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0018_alter_businesspartner_refered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='referer_mobile',
            field=models.CharField(default='', max_length=15, unique=True, validators=[BusinessPartner.models.validate_mobile_no], verbose_name='Referrer Mobile No'),
            preserve_default=False,
        ),
    ]
