# Generated by Django 5.1.4 on 2025-02-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='created_at',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='production',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
