# Generated by Django 5.1.4 on 2025-02-05 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_created_at_production_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedproduct',
            name='name',
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='production',
            name='finished_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='inventory.finishedproduct'),
        ),
    ]
