# Generated by Django 5.1.4 on 2025-01-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDashboardMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Project Owner'), ('admin', 'Super User'), ('staff', 'Key User'), ('craftsman', 'Craftsman'), ('seller', 'End User'), ('customer', 'One Time User')], max_length=50)),
                ('dashboard_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resuser',
            name='permission_group',
        ),
        migrations.RemoveField(
            model_name='resuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='resuser',
            name='role',
        ),
        migrations.AddField(
            model_name='resuser',
            name='approve',
            field=models.BooleanField(default=False, verbose_name='Approve'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='copy',
            field=models.BooleanField(default=False, verbose_name='Copy'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='custom_access',
            field=models.BooleanField(default=False, verbose_name='Custom Access'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='download',
            field=models.BooleanField(default=False, verbose_name='Download'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='edit',
            field=models.BooleanField(default=False, verbose_name='Edit'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='full_control',
            field=models.BooleanField(default=False, verbose_name='Full Control'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='manage_roles',
            field=models.BooleanField(default=False, verbose_name='Manage Roles'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='print_perm',
            field=models.BooleanField(default=False, verbose_name='Print'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='reject',
            field=models.BooleanField(default=False, verbose_name='Reject'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='restore',
            field=models.BooleanField(default=False, verbose_name='Restore'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='screenshot',
            field=models.BooleanField(default=False, verbose_name='Screenshot'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='share',
            field=models.BooleanField(default=False, verbose_name='Share'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='transfer',
            field=models.BooleanField(default=False, verbose_name='Transfer'),
        ),
        migrations.AddField(
            model_name='resuser',
            name='view_only',
            field=models.BooleanField(default=False, verbose_name='View Only'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
    ]
