# Generated by Django 5.1.4 on 2025-01-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_roledashboardmapping_remove_resuser_permission_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resuser',
            name='user_code',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='User Code'),
        ),
    ]
