# Generated by Django 5.1.4 on 2025-01-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_resuser_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='resuser',
            name='user_state',
            field=models.CharField(choices=[('internal', 'INTERNAL USER'), ('external', 'EXTERNAL USER')], default='inernal', max_length=50, verbose_name='User_state'),
        ),
    ]
