# Generated by Django 5.1.4 on 2025-01-31 13:11

import django.core.validators
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_resuser_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resuser',
            name='email_id',
            field=models.EmailField(max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator('Enter a valid email address.')], verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='mobile_no',
            field=models.CharField(max_length=15, validators=[user.models.validate_mobile_no], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='user_state',
            field=models.CharField(choices=[('internal', 'INTERNAL USER'), ('external', 'EXTERNAL USER')], default='internal', max_length=50, verbose_name='User State'),
        ),
    ]
