# Generated by Django 5.1.4 on 2025-01-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=100, unique=True)),
                ('category', models.CharField(blank=True, choices=[('Rings', 'Rings'), ('Chains', 'Chains'), ('Pendants', 'Pendants'), ('Bangles', 'Bangles'), ('Anklets', 'Anklets'), ('Necklaces', 'Necklaces'), ('Bracelets', 'Bracelets'), ('Earrings', 'Earrings')], max_length=50, null=True)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_unit', models.CharField(blank=True, choices=[('mg', 'Milligram'), ('g', 'Gram'), ('kg', 'Kilogram'), ('oz', 'Ounce'), ('lb', 'Pound')], max_length=2, null=True)),
                ('size', models.CharField(blank=True, choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], max_length=50, null=True)),
                ('stone', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
                ('rodium', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
                ('hallmark', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
                ('screw', models.CharField(blank=True, choices=[('Closed', 'Closed'), ('Open', 'Open')], max_length=50, null=True)),
                ('hook', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('order_image', models.ImageField(blank=True, null=True, upload_to='order_images/')),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
