# Generated by Django 5.1.4 on 2025-02-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_rodium_order_rhodium_order_assign_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='rhodium',
            new_name='rodium',
        ),
    ]
