# Generated by Django 5.1.4 on 2025-02-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_rhodium_order_rodium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
