# Generated by Django 5.1.4 on 2025-01-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_end_date_order_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('accepted', 'accepted'), ('progress', 'in progress'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
