# Generated by Django 5.1.4 on 2025-03-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
