# Generated by Django 5.1.5 on 2025-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='text_assign_user',
            new_name='assign_remarks',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='weight_unit',
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_by',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='barcoded_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='bp_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='branch_code',
            field=models.CharField(default='DEFAULT_BRANCH', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='collection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='console_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='design',
            field=models.CharField(default='DEFAULT_DESIGN', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='dtype',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('custom', 'Custom')], default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='enamel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='finish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hbt_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='metal_colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Unnamed Order', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='open_close',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('preorder', 'Preorder')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='polish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(default='Default Product', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='purity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_no',
            field=models.CharField(default='REF001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sub_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='supplied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tolerance_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tolerance_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_design',
            field=models.CharField(default='DEFAULT_DESIGN', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='work_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
