# Generated by Django 5.1.5 on 2025-03-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_user_alter_order_bp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
