# Generated by Django 5.1.5 on 2025-03-19 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0007_rename_name_businesspartner_full_name_and_more'),
        ('order', '0010_alter_order_bp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bp_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BusinessPartner.businesspartner'),
        ),
    ]
