# Generated by Django 5.1.5 on 2025-03-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_bp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bp_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
