# Generated by Django 5.1.5 on 2025-03-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
