# Generated by Django 5.1.5 on 2025-03-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in-process', 'In Process'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
