# Generated by Django 5.1.5 on 2025-04-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='role',
            field=models.CharField(blank=True, choices=[('BUYER', 'BUYER'), ('CRAFTSMAN', 'CRAFTSMAN')], max_length=20, null=True),
        ),
    ]
